application: prodapp
version: 1
runtime: php55
api_version: 1
module: default

handlers:

- url: /
  script: guide_home.php

- url: /index\.html
  script: index.php

- url: /css
  static_dir: css

- url: /assets
  static_dir: assets

- url: /img
  static_dir: img

- url: /images
  static_dir: images

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: admin.php
  login: admin

- url: /(.+\.php)$
  script: \1
